name: atirnayab document upload
description: this is sample to test market place
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
inputs:
  file:
    description: "Relative path to the documentation file"
    required: true
    default: api-contract.yml
  doc:
    description: "Documentation id. Can be found in the documentation settings on https://bump.sh"
  token:
    description: "Documentation token. Can be found in the documentation settings on https://bump.sh"
runs:
  using: "node14"
  main: "index.js"
branding:
  color: gray-dark
  icon: book-open
