name: atirnayab document upload
description: this is sample to test market place
inputs:
  PATH:
    description: "file path"
    required: true
  PROJECT_KEY:
    description: "project key"
    required: true
  SECRET:
    description: "github secret key"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: gray-dark
  icon: book-open
