name: atirnayab document upload
description: this is sample to test market place
jobs:
  api-diff:
    name: Check API diff
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
inputs:
  file:
    description: "Relative path to the documentation file"
    required: true
    default: api-contract.yml
  doc:
    description: "Documentation id. Can be found in the documentation settings on https://bump.sh"
  token:
    description: "Documentation token. Can be found in the documentation settings on https://bump.sh"
runs:
  using: "node12"
  main: "index.js"
branding:
  color: gray-dark
  icon: book-open
